# Base image (choose a suitable Node.js version)
FROM node:18-alpine 

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock)
COPY package*.json ./

# Install dependencies (use npm or yarn)
RUN npm install

# Copy the rest of your project files
COPY . .

RUN npm run build

# Expose port 80 (default for web servers)
EXPOSE 3001

# Serve the application
CMD ["npm", "run","preview"]